name: Publish Helm Chart

on:
  push:
    tags:
      - 'kit-ar/pub/v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Build Helm Chart
        run: helm package ./helm/cf-tunnel-v3

      - name: Push Helm Chart to OCI registry
        run: |
          helm push cf-tunnel-v3-3.1011.240803.tgz oci://ghcr.io/pabaquino/helm-charts

      - name: Confirm upload
        run: helm search repo oci://ghcr.io/pabaquino/helm-charts