name: Publish Helm Chart

on:
  push:
    tags:
      - 'kit-ar/pub/v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install yq to parse YAML
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.30.6/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      # Extract the chart version from Chart.yaml
      - name: Get Chart Version
        id: get_version
        run: |
          CHART_VERSION=$(yq eval '.version' ./helm/cf-tunnel-v3/Chart.yaml)
          echo "Chart version is: $CHART_VERSION"
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Build Helm Chart
        run: helm package ./helm/cf-tunnel-v3 --version ${{ env.CHART_VERSION }}

      - name: Push Helm Chart to OCI registry
        run: |
          helm push cf-tunnel-v3-${{ env.CHART_VERSION }}.tgz oci://ghcr.io/pabaquino/helm-charts

      - name: Confirm upload
        run: helm show chart oci://ghcr.io/pabaquino/helm-charts/cf-tunnel-v3 --version ${{ env.CHART_VERSION }}
